# Generated by Django 6.0 on 2026-01-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
